window.setInterval(function(){
   window.setTimeout(function(){
       window.setTimeout(function(){
                  window.setTimeout(function(){
                        window.setTimeout(function(){
                            $("#logo2").css('background-image','url(images/logo-anim1.png)');
                        },1000);   
                     $("#logo2").css('background-image','url(images/logo-anim2.png)');
                  },1000);         
          $("#logo2").css('background-image','url(images/logo-anim3.png)');
      },1000);
      $("#logo2").css('background-image','url(images/logo-anim4.png)');
   },1000);
      $("#logo2").css('background-image','url(images/logo-anim5.png)');
},2000);